version: '3'
name: nova-chat

services:
  np-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  io-service:
    build:
      context: ./io_service
      dockerfile: Dockerfile
    environment:
      - AZURE_KEY="b96fde6174d945ec8d91219bfc87896e"
      - AZURE_REGION="eastus"
    ports:
      - "8080:8080"

  nlp_processor:
    container_name: nlp_processor
    build:
      context: ./nlp_processor
      dockerfile: Dockerfile
    ports:
      - "7034:443"
      - "5058:80"
    env_file: nlp_processor/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
